services:
  auth-deporcanchas:
    build: .
    image: josedmg/auth-deporcanchas:0.1
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_URL: ${DB_URL}
      DB_NAME: ${DB_NAME}
    depends_on:
      auth-db:
        condition: service_healthy
    restart: unless-stopped

  auth-db:
    image: postgres:16
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 5s
      timeout: 5s
      retries: 5
